<?xml version="1.0" encoding="ascii"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
          "DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>lib.common.errors</title>
  <link rel="stylesheet" href="epydoc.css" type="text/css" />
  <script type="text/javascript" src="epydoc.js"></script>
</head>

<body bgcolor="white" text="black" link="blue" vlink="#204080"
      alink="#204080">
<!-- ==================== NAVIGATION BAR ==================== -->
<table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">

  <!-- Tree link -->
      <th>&nbsp;&nbsp;&nbsp;<a
        href="module-tree.html">Trees</a>&nbsp;&nbsp;&nbsp;</th>

  <!-- Index link -->
      <th>&nbsp;&nbsp;&nbsp;<a
        href="identifier-index.html">Indices</a>&nbsp;&nbsp;&nbsp;</th>

  <!-- Help link -->
      <th>&nbsp;&nbsp;&nbsp;<a
        href="help.html">Help</a>&nbsp;&nbsp;&nbsp;</th>

  <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://cuckoosandbox.org">Cuckoo Sandbox</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="lib-module.html">Package&nbsp;lib</a> ::
        <a href="lib.common-module.html">Package&nbsp;common</a> ::
        Module&nbsp;errors
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="lib.common.errors-pysrc.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Source Code for <a href="lib.common.errors-module.html">Module lib.common.errors</a></h1>
<pre class="py-src">
<a name="L1"></a><tt class="py-lineno">  1</tt>  <tt class="py-line"><tt class="py-comment"># Copyright (C) 2010-2013 Claudio Guarnieri.</tt> </tt>
<a name="L2"></a><tt class="py-lineno">  2</tt>  <tt class="py-line"><tt class="py-comment"># Copyright (C) 2014-2015 Cuckoo Foundation.</tt> </tt>
<a name="L3"></a><tt class="py-lineno">  3</tt>  <tt class="py-line"><tt class="py-comment"># This file is part of Cuckoo Sandbox - http://www.cuckoosandbox.org</tt> </tt>
<a name="L4"></a><tt class="py-lineno">  4</tt>  <tt class="py-line"><tt class="py-comment"># See the file 'docs/LICENSE' for copying permission.</tt> </tt>
<a name="L5"></a><tt class="py-lineno">  5</tt>  <tt class="py-line"> </tt>
<a name="L6"></a><tt class="py-lineno">  6</tt>  <tt class="py-line"><tt id="link-0" class="py-name" targets="Variable lib.common.errors.ERRORS=lib.common.errors-module.html#ERRORS"><a title="lib.common.errors.ERRORS" class="py-name" href="#" onclick="return doclink('link-0', 'ERRORS', 'link-0');">ERRORS</a></tt> <tt class="py-op">=</tt> <tt class="py-op">{</tt> </tt>
<a name="L7"></a><tt class="py-lineno">  7</tt>  <tt class="py-line"> <tt class="py-number">0</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operation completed successfully"</tt><tt class="py-op">,</tt> </tt>
<a name="L8"></a><tt class="py-lineno">  8</tt>  <tt class="py-line">     <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SUCCESS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L9"></a><tt class="py-lineno">  9</tt>  <tt class="py-line"> <tt class="py-number">1</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Incorrect function"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_FUNCTION"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L10"></a><tt class="py-lineno"> 10</tt>  <tt class="py-line"> <tt class="py-number">2</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system cannot find the file specified"</tt><tt class="py-op">,</tt> </tt>
<a name="L11"></a><tt class="py-lineno"> 11</tt>  <tt class="py-line">     <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_FILE_NOT_FOUND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L12"></a><tt class="py-lineno"> 12</tt>  <tt class="py-line"> <tt class="py-number">3</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system cannot find the path specified"</tt><tt class="py-op">,</tt> </tt>
<a name="L13"></a><tt class="py-lineno"> 13</tt>  <tt class="py-line">     <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_PATH_NOT_FOUND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L14"></a><tt class="py-lineno"> 14</tt>  <tt class="py-line"> <tt class="py-number">4</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system cannot open the file"</tt><tt class="py-op">,</tt> </tt>
<a name="L15"></a><tt class="py-lineno"> 15</tt>  <tt class="py-line">     <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_TOO_MANY_OPEN_FILES"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L16"></a><tt class="py-lineno"> 16</tt>  <tt class="py-line"> <tt class="py-number">5</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Access is denied"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_ACCESS_DENIED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L17"></a><tt class="py-lineno"> 17</tt>  <tt class="py-line"> <tt class="py-number">6</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The handle is invalid"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_HANDLE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L18"></a><tt class="py-lineno"> 18</tt>  <tt class="py-line"> <tt class="py-number">7</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The storage control blocks were destroyed"</tt><tt class="py-op">,</tt> </tt>
<a name="L19"></a><tt class="py-lineno"> 19</tt>  <tt class="py-line">     <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_ARENA_TRASHED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L20"></a><tt class="py-lineno"> 20</tt>  <tt class="py-line"> <tt class="py-number">8</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Not enough storage is available to process this command"</tt><tt class="py-op">,</tt> </tt>
<a name="L21"></a><tt class="py-lineno"> 21</tt>  <tt class="py-line">     <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NOT_ENOUGH_MEMORY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L22"></a><tt class="py-lineno"> 22</tt>  <tt class="py-line"> <tt class="py-number">9</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The storage control block address is invalid"</tt><tt class="py-op">,</tt> </tt>
<a name="L23"></a><tt class="py-lineno"> 23</tt>  <tt class="py-line">     <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_BLOCK"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L24"></a><tt class="py-lineno"> 24</tt>  <tt class="py-line"> <tt class="py-number">10</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The environment is incorrect"</tt><tt class="py-op">,</tt> </tt>
<a name="L25"></a><tt class="py-lineno"> 25</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_ENVIRONMENT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L26"></a><tt class="py-lineno"> 26</tt>  <tt class="py-line"> <tt class="py-number">11</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An attempt was made to load a program with an incorrect format"</tt><tt class="py-op">,</tt> </tt>
<a name="L27"></a><tt class="py-lineno"> 27</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_FORMAT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L28"></a><tt class="py-lineno"> 28</tt>  <tt class="py-line"> <tt class="py-number">12</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The access code is invalid"</tt><tt class="py-op">,</tt> </tt>
<a name="L29"></a><tt class="py-lineno"> 29</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_ACCESS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L30"></a><tt class="py-lineno"> 30</tt>  <tt class="py-line"> <tt class="py-number">13</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The data is invalid"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_DATA"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L31"></a><tt class="py-lineno"> 31</tt>  <tt class="py-line"> <tt class="py-number">14</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Not enough storage is available to complete this operation"</tt><tt class="py-op">,</tt> </tt>
<a name="L32"></a><tt class="py-lineno"> 32</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_OUTOFMEMORY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L33"></a><tt class="py-lineno"> 33</tt>  <tt class="py-line"> <tt class="py-number">15</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system cannot find the drive specified"</tt><tt class="py-op">,</tt> </tt>
<a name="L34"></a><tt class="py-lineno"> 34</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_DRIVE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L35"></a><tt class="py-lineno"> 35</tt>  <tt class="py-line"> <tt class="py-number">16</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The directory cannot be removed"</tt><tt class="py-op">,</tt> </tt>
<a name="L36"></a><tt class="py-lineno"> 36</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_CURRENT_DIRECTORY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L37"></a><tt class="py-lineno"> 37</tt>  <tt class="py-line"> <tt class="py-number">17</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system cannot move the file to a different disk drive"</tt><tt class="py-op">,</tt> </tt>
<a name="L38"></a><tt class="py-lineno"> 38</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NOT_SAME_DEVICE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L39"></a><tt class="py-lineno"> 39</tt>  <tt class="py-line"> <tt class="py-number">18</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"There are no more files"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NO_MORE_FILES"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L40"></a><tt class="py-lineno"> 40</tt>  <tt class="py-line"> <tt class="py-number">19</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The media is write protected"</tt><tt class="py-op">,</tt> </tt>
<a name="L41"></a><tt class="py-lineno"> 41</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_WRITE_PROTECT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L42"></a><tt class="py-lineno"> 42</tt>  <tt class="py-line"> <tt class="py-number">20</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system cannot find the device specified"</tt><tt class="py-op">,</tt> </tt>
<a name="L43"></a><tt class="py-lineno"> 43</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_UNIT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L44"></a><tt class="py-lineno"> 44</tt>  <tt class="py-line"> <tt class="py-number">21</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The device is not ready"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NOT_READY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L45"></a><tt class="py-lineno"> 45</tt>  <tt class="py-line"> <tt class="py-number">22</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The device does not recognize the command"</tt><tt class="py-op">,</tt> </tt>
<a name="L46"></a><tt class="py-lineno"> 46</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_COMMAND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L47"></a><tt class="py-lineno"> 47</tt>  <tt class="py-line"> <tt class="py-number">23</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Data error (cyclic redundancy check)"</tt><tt class="py-op">,</tt> </tt>
<a name="L48"></a><tt class="py-lineno"> 48</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_CRC"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L49"></a><tt class="py-lineno"> 49</tt>  <tt class="py-line"> <tt class="py-number">24</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The program issued a command but the command length is incorrect"</tt><tt class="py-op">,</tt> </tt>
<a name="L50"></a><tt class="py-lineno"> 50</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_LENGTH"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L51"></a><tt class="py-lineno"> 51</tt>  <tt class="py-line"> <tt class="py-number">25</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The drive cannot locate a specific area or track on the disk"</tt><tt class="py-op">,</tt> </tt>
<a name="L52"></a><tt class="py-lineno"> 52</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SEEK"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L53"></a><tt class="py-lineno"> 53</tt>  <tt class="py-line"> <tt class="py-number">26</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The specified disk or diskette cannot be accessed"</tt><tt class="py-op">,</tt> </tt>
<a name="L54"></a><tt class="py-lineno"> 54</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NOT_DOS_DISK"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L55"></a><tt class="py-lineno"> 55</tt>  <tt class="py-line"> <tt class="py-number">27</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The drive cannot find the sector requested"</tt><tt class="py-op">,</tt> </tt>
<a name="L56"></a><tt class="py-lineno"> 56</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SECTOR_NOT_FOUND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L57"></a><tt class="py-lineno"> 57</tt>  <tt class="py-line"> <tt class="py-number">28</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The printer is out of paper"</tt><tt class="py-op">,</tt> </tt>
<a name="L58"></a><tt class="py-lineno"> 58</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_OUT_OF_PAPER"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L59"></a><tt class="py-lineno"> 59</tt>  <tt class="py-line"> <tt class="py-number">29</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system cannot write to the specified device"</tt><tt class="py-op">,</tt> </tt>
<a name="L60"></a><tt class="py-lineno"> 60</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_WRITE_FAULT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L61"></a><tt class="py-lineno"> 61</tt>  <tt class="py-line"> <tt class="py-number">30</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system cannot read from the specified device"</tt><tt class="py-op">,</tt> </tt>
<a name="L62"></a><tt class="py-lineno"> 62</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_READ_FAULT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L63"></a><tt class="py-lineno"> 63</tt>  <tt class="py-line"> <tt class="py-number">31</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"A device attached to the system is not functioning"</tt><tt class="py-op">,</tt> </tt>
<a name="L64"></a><tt class="py-lineno"> 64</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_GEN_FAILURE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L65"></a><tt class="py-lineno"> 65</tt>  <tt class="py-line"> <tt class="py-number">32</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The process cannot access the file because it is being used by another process"</tt><tt class="py-op">,</tt> </tt>
<a name="L66"></a><tt class="py-lineno"> 66</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SHARING_VIOLATION"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L67"></a><tt class="py-lineno"> 67</tt>  <tt class="py-line"> <tt class="py-number">33</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The process cannot access the file because another process has locked a portion of the file"</tt><tt class="py-op">,</tt> </tt>
<a name="L68"></a><tt class="py-lineno"> 68</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_LOCK_VIOLATION"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L69"></a><tt class="py-lineno"> 69</tt>  <tt class="py-line"> <tt class="py-number">34</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The wrong diskette is in the drive. Insert %2 (Volume Serial Number: %3) into drive %1"</tt><tt class="py-op">,</tt> </tt>
<a name="L70"></a><tt class="py-lineno"> 70</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_WRONG_DISK"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L71"></a><tt class="py-lineno"> 71</tt>  <tt class="py-line"> <tt class="py-number">36</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Too many files opened for sharing"</tt><tt class="py-op">,</tt> </tt>
<a name="L72"></a><tt class="py-lineno"> 72</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SHARING_BUFFER_EXCEEDED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L73"></a><tt class="py-lineno"> 73</tt>  <tt class="py-line"> <tt class="py-number">38</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Reached the end of the file"</tt><tt class="py-op">,</tt> </tt>
<a name="L74"></a><tt class="py-lineno"> 74</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_HANDLE_EOF"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L75"></a><tt class="py-lineno"> 75</tt>  <tt class="py-line"> <tt class="py-number">39</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The disk is full"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_HANDLE_DISK_FULL"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L76"></a><tt class="py-lineno"> 76</tt>  <tt class="py-line"> <tt class="py-number">50</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The request is not supported"</tt><tt class="py-op">,</tt> </tt>
<a name="L77"></a><tt class="py-lineno"> 77</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NOT_SUPPORTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L78"></a><tt class="py-lineno"> 78</tt>  <tt class="py-line"> <tt class="py-number">51</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Windows cannot find the network path. Verify that the network path is correct and the destination computer is not busy or turned off. If Windows still cannot find the network path, contact your network administrator"</tt><tt class="py-op">,</tt> </tt>
<a name="L79"></a><tt class="py-lineno"> 79</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_REM_NOT_LIST"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L80"></a><tt class="py-lineno"> 80</tt>  <tt class="py-line"> <tt class="py-number">52</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"You were not connected because a duplicate name exists on the network. If joining a domain, go to System in Control Panel to change the computer name and try again. If joining a workgroup, choose another workgroup name"</tt><tt class="py-op">,</tt> </tt>
<a name="L81"></a><tt class="py-lineno"> 81</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DUP_NAME"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L82"></a><tt class="py-lineno"> 82</tt>  <tt class="py-line"> <tt class="py-number">53</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The network path was not found"</tt><tt class="py-op">,</tt> </tt>
<a name="L83"></a><tt class="py-lineno"> 83</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_NETPATH"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L84"></a><tt class="py-lineno"> 84</tt>  <tt class="py-line"> <tt class="py-number">54</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The network is busy"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NETWORK_BUSY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L85"></a><tt class="py-lineno"> 85</tt>  <tt class="py-line"> <tt class="py-number">55</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The specified network resource or device is no longer available"</tt><tt class="py-op">,</tt> </tt>
<a name="L86"></a><tt class="py-lineno"> 86</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DEV_NOT_EXIST"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L87"></a><tt class="py-lineno"> 87</tt>  <tt class="py-line"> <tt class="py-number">56</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The network BIOS command limit has been reached"</tt><tt class="py-op">,</tt> </tt>
<a name="L88"></a><tt class="py-lineno"> 88</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_TOO_MANY_CMDS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L89"></a><tt class="py-lineno"> 89</tt>  <tt class="py-line"> <tt class="py-number">57</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"A network adapter hardware error occurred"</tt><tt class="py-op">,</tt> </tt>
<a name="L90"></a><tt class="py-lineno"> 90</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_ADAP_HDW_ERR"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L91"></a><tt class="py-lineno"> 91</tt>  <tt class="py-line"> <tt class="py-number">58</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The specified server cannot perform the requested operation"</tt><tt class="py-op">,</tt> </tt>
<a name="L92"></a><tt class="py-lineno"> 92</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_NET_RESP"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L93"></a><tt class="py-lineno"> 93</tt>  <tt class="py-line"> <tt class="py-number">59</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An unexpected network error occurred"</tt><tt class="py-op">,</tt> </tt>
<a name="L94"></a><tt class="py-lineno"> 94</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_UNEXP_NET_ERR"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L95"></a><tt class="py-lineno"> 95</tt>  <tt class="py-line"> <tt class="py-number">60</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The remote adapter is not compatible"</tt><tt class="py-op">,</tt> </tt>
<a name="L96"></a><tt class="py-lineno"> 96</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_REM_ADAP"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L97"></a><tt class="py-lineno"> 97</tt>  <tt class="py-line"> <tt class="py-number">61</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The printer queue is full"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_PRINTQ_FULL"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L98"></a><tt class="py-lineno"> 98</tt>  <tt class="py-line"> <tt class="py-number">62</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Space to store the file waiting to be printed is not available on the server"</tt><tt class="py-op">,</tt> </tt>
<a name="L99"></a><tt class="py-lineno"> 99</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NO_SPOOL_SPACE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L100"></a><tt class="py-lineno">100</tt>  <tt class="py-line"> <tt class="py-number">63</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Your file waiting to be printed was deleted"</tt><tt class="py-op">,</tt> </tt>
<a name="L101"></a><tt class="py-lineno">101</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_PRINT_CANCELLED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L102"></a><tt class="py-lineno">102</tt>  <tt class="py-line"> <tt class="py-number">64</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The specified network name is no longer available"</tt><tt class="py-op">,</tt> </tt>
<a name="L103"></a><tt class="py-lineno">103</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NETNAME_DELETED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L104"></a><tt class="py-lineno">104</tt>  <tt class="py-line"> <tt class="py-number">65</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Network access is denied"</tt><tt class="py-op">,</tt> </tt>
<a name="L105"></a><tt class="py-lineno">105</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NETWORK_ACCESS_DENIED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L106"></a><tt class="py-lineno">106</tt>  <tt class="py-line"> <tt class="py-number">66</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The network resource type is not correct"</tt><tt class="py-op">,</tt> </tt>
<a name="L107"></a><tt class="py-lineno">107</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_DEV_TYPE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L108"></a><tt class="py-lineno">108</tt>  <tt class="py-line"> <tt class="py-number">67</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The network name cannot be found"</tt><tt class="py-op">,</tt> </tt>
<a name="L109"></a><tt class="py-lineno">109</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_NET_NAME"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L110"></a><tt class="py-lineno">110</tt>  <tt class="py-line"> <tt class="py-number">68</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The name limit for the local computer network adapter card was exceeded"</tt><tt class="py-op">,</tt> </tt>
<a name="L111"></a><tt class="py-lineno">111</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_TOO_MANY_NAMES"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L112"></a><tt class="py-lineno">112</tt>  <tt class="py-line"> <tt class="py-number">69</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The network BIOS session limit was exceeded"</tt><tt class="py-op">,</tt> </tt>
<a name="L113"></a><tt class="py-lineno">113</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_TOO_MANY_SESS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L114"></a><tt class="py-lineno">114</tt>  <tt class="py-line"> <tt class="py-number">70</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The remote server has been paused or is in the process of being started"</tt><tt class="py-op">,</tt> </tt>
<a name="L115"></a><tt class="py-lineno">115</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SHARING_PAUSED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L116"></a><tt class="py-lineno">116</tt>  <tt class="py-line"> <tt class="py-number">71</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"No more connections can be made to this remote computer at this time because there are already as many connections as the computer can accept"</tt><tt class="py-op">,</tt> </tt>
<a name="L117"></a><tt class="py-lineno">117</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_REQ_NOT_ACCEP"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L118"></a><tt class="py-lineno">118</tt>  <tt class="py-line"> <tt class="py-number">72</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The specified printer or disk device has been paused"</tt><tt class="py-op">,</tt> </tt>
<a name="L119"></a><tt class="py-lineno">119</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_REDIR_PAUSED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L120"></a><tt class="py-lineno">120</tt>  <tt class="py-line"> <tt class="py-number">80</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The file exists"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_FILE_EXISTS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L121"></a><tt class="py-lineno">121</tt>  <tt class="py-line"> <tt class="py-number">82</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The directory or file cannot be created"</tt><tt class="py-op">,</tt> </tt>
<a name="L122"></a><tt class="py-lineno">122</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_CANNOT_MAKE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L123"></a><tt class="py-lineno">123</tt>  <tt class="py-line"> <tt class="py-number">83</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Fail on INT 24"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_FAIL_I24"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L124"></a><tt class="py-lineno">124</tt>  <tt class="py-line"> <tt class="py-number">84</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Storage to process this request is not available"</tt><tt class="py-op">,</tt> </tt>
<a name="L125"></a><tt class="py-lineno">125</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_OUT_OF_STRUCTURES"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L126"></a><tt class="py-lineno">126</tt>  <tt class="py-line"> <tt class="py-number">85</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The local device name is already in use"</tt><tt class="py-op">,</tt> </tt>
<a name="L127"></a><tt class="py-lineno">127</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_ALREADY_ASSIGNED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L128"></a><tt class="py-lineno">128</tt>  <tt class="py-line"> <tt class="py-number">86</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The specified network password is not correct"</tt><tt class="py-op">,</tt> </tt>
<a name="L129"></a><tt class="py-lineno">129</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_PASSWORD"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L130"></a><tt class="py-lineno">130</tt>  <tt class="py-line"> <tt class="py-number">87</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The parameter is incorrect"</tt><tt class="py-op">,</tt> </tt>
<a name="L131"></a><tt class="py-lineno">131</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_PARAMETER"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L132"></a><tt class="py-lineno">132</tt>  <tt class="py-line"> <tt class="py-number">88</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"A write fault occurred on the network"</tt><tt class="py-op">,</tt> </tt>
<a name="L133"></a><tt class="py-lineno">133</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NET_WRITE_FAULT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L134"></a><tt class="py-lineno">134</tt>  <tt class="py-line"> <tt class="py-number">89</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system cannot start another process at this time"</tt><tt class="py-op">,</tt> </tt>
<a name="L135"></a><tt class="py-lineno">135</tt>  <tt class="py-line">      <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NO_PROC_SLOTS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L136"></a><tt class="py-lineno">136</tt>  <tt class="py-line"> <tt class="py-number">100</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Cannot create another system semaphore"</tt><tt class="py-op">,</tt> </tt>
<a name="L137"></a><tt class="py-lineno">137</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_TOO_MANY_SEMAPHORES"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L138"></a><tt class="py-lineno">138</tt>  <tt class="py-line"> <tt class="py-number">101</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The exclusive semaphore is owned by another process"</tt><tt class="py-op">,</tt> </tt>
<a name="L139"></a><tt class="py-lineno">139</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_EXCL_SEM_ALREADY_OWNED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L140"></a><tt class="py-lineno">140</tt>  <tt class="py-line"> <tt class="py-number">102</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The semaphore is set and cannot be closed"</tt><tt class="py-op">,</tt> </tt>
<a name="L141"></a><tt class="py-lineno">141</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SEM_IS_SET"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L142"></a><tt class="py-lineno">142</tt>  <tt class="py-line"> <tt class="py-number">103</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The semaphore cannot be set again"</tt><tt class="py-op">,</tt> </tt>
<a name="L143"></a><tt class="py-lineno">143</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_TOO_MANY_SEM_REQUESTS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L144"></a><tt class="py-lineno">144</tt>  <tt class="py-line"> <tt class="py-number">104</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Cannot request exclusive semaphores at interrupt time"</tt><tt class="py-op">,</tt> </tt>
<a name="L145"></a><tt class="py-lineno">145</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_AT_INTERRUPT_TIME"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L146"></a><tt class="py-lineno">146</tt>  <tt class="py-line"> <tt class="py-number">105</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The previous ownership of this semaphore has ended"</tt><tt class="py-op">,</tt> </tt>
<a name="L147"></a><tt class="py-lineno">147</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SEM_OWNER_DIED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L148"></a><tt class="py-lineno">148</tt>  <tt class="py-line"> <tt class="py-number">106</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Insert the diskette for drive %1"</tt><tt class="py-op">,</tt> </tt>
<a name="L149"></a><tt class="py-lineno">149</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SEM_USER_LIMIT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L150"></a><tt class="py-lineno">150</tt>  <tt class="py-line"> <tt class="py-number">107</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The program stopped because an alternate diskette was not inserted"</tt><tt class="py-op">,</tt> </tt>
<a name="L151"></a><tt class="py-lineno">151</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DISK_CHANGE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L152"></a><tt class="py-lineno">152</tt>  <tt class="py-line"> <tt class="py-number">108</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The disk is in use or locked by another process"</tt><tt class="py-op">,</tt> </tt>
<a name="L153"></a><tt class="py-lineno">153</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DRIVE_LOCKED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L154"></a><tt class="py-lineno">154</tt>  <tt class="py-line"> <tt class="py-number">109</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The pipe has been ended"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BROKEN_PIPE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L155"></a><tt class="py-lineno">155</tt>  <tt class="py-line"> <tt class="py-number">110</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system cannot open the device or file specified"</tt><tt class="py-op">,</tt> </tt>
<a name="L156"></a><tt class="py-lineno">156</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_OPEN_FAILED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L157"></a><tt class="py-lineno">157</tt>  <tt class="py-line"> <tt class="py-number">111</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The file name is too long"</tt><tt class="py-op">,</tt> </tt>
<a name="L158"></a><tt class="py-lineno">158</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BUFFER_OVERFLOW"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L159"></a><tt class="py-lineno">159</tt>  <tt class="py-line"> <tt class="py-number">112</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"There is not enough space on the disk"</tt><tt class="py-op">,</tt> </tt>
<a name="L160"></a><tt class="py-lineno">160</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DISK_FULL"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L161"></a><tt class="py-lineno">161</tt>  <tt class="py-line"> <tt class="py-number">113</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"No more internal file identifiers available"</tt><tt class="py-op">,</tt> </tt>
<a name="L162"></a><tt class="py-lineno">162</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NO_MORE_SEARCH_HANDLES"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L163"></a><tt class="py-lineno">163</tt>  <tt class="py-line"> <tt class="py-number">114</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The target internal file identifier is incorrect"</tt><tt class="py-op">,</tt> </tt>
<a name="L164"></a><tt class="py-lineno">164</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_TARGET_HANDLE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L165"></a><tt class="py-lineno">165</tt>  <tt class="py-line"> <tt class="py-number">117</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The IOCTL call made by the application program is not correct"</tt><tt class="py-op">,</tt> </tt>
<a name="L166"></a><tt class="py-lineno">166</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_CATEGORY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L167"></a><tt class="py-lineno">167</tt>  <tt class="py-line"> <tt class="py-number">118</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The verify-on-write switch parameter value is not correct"</tt><tt class="py-op">,</tt> </tt>
<a name="L168"></a><tt class="py-lineno">168</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_VERIFY_SWITCH"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L169"></a><tt class="py-lineno">169</tt>  <tt class="py-line"> <tt class="py-number">119</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system does not support the command requested"</tt><tt class="py-op">,</tt> </tt>
<a name="L170"></a><tt class="py-lineno">170</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_DRIVER_LEVEL"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L171"></a><tt class="py-lineno">171</tt>  <tt class="py-line"> <tt class="py-number">120</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"This function is not supported on this system"</tt><tt class="py-op">,</tt> </tt>
<a name="L172"></a><tt class="py-lineno">172</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_CALL_NOT_IMPLEMENTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L173"></a><tt class="py-lineno">173</tt>  <tt class="py-line"> <tt class="py-number">121</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The semaphore timeout period has expired"</tt><tt class="py-op">,</tt> </tt>
<a name="L174"></a><tt class="py-lineno">174</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SEM_TIMEOUT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L175"></a><tt class="py-lineno">175</tt>  <tt class="py-line"> <tt class="py-number">122</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The data area passed to a system call is too small"</tt><tt class="py-op">,</tt> </tt>
<a name="L176"></a><tt class="py-lineno">176</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INSUFFICIENT_BUFFER"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L177"></a><tt class="py-lineno">177</tt>  <tt class="py-line"> <tt class="py-number">123</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The filename, directory name, or volume label syntax is incorrect"</tt><tt class="py-op">,</tt> </tt>
<a name="L178"></a><tt class="py-lineno">178</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_NAME"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L179"></a><tt class="py-lineno">179</tt>  <tt class="py-line"> <tt class="py-number">124</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system call level is not correct"</tt><tt class="py-op">,</tt> </tt>
<a name="L180"></a><tt class="py-lineno">180</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_LEVEL"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L181"></a><tt class="py-lineno">181</tt>  <tt class="py-line"> <tt class="py-number">125</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The disk has no volume label"</tt><tt class="py-op">,</tt> </tt>
<a name="L182"></a><tt class="py-lineno">182</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NO_VOLUME_LABEL"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L183"></a><tt class="py-lineno">183</tt>  <tt class="py-line"> <tt class="py-number">126</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The specified module could not be found"</tt><tt class="py-op">,</tt> </tt>
<a name="L184"></a><tt class="py-lineno">184</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_MOD_NOT_FOUND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L185"></a><tt class="py-lineno">185</tt>  <tt class="py-line"> <tt class="py-number">127</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The specified procedure could not be found"</tt><tt class="py-op">,</tt> </tt>
<a name="L186"></a><tt class="py-lineno">186</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_PROC_NOT_FOUND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L187"></a><tt class="py-lineno">187</tt>  <tt class="py-line"> <tt class="py-number">128</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"There are no child processes to wait for"</tt><tt class="py-op">,</tt> </tt>
<a name="L188"></a><tt class="py-lineno">188</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_WAIT_NO_CHILDREN"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L189"></a><tt class="py-lineno">189</tt>  <tt class="py-line"> <tt class="py-number">129</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The %1 application cannot be run in Win32 mode"</tt><tt class="py-op">,</tt> </tt>
<a name="L190"></a><tt class="py-lineno">190</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_CHILD_NOT_COMPLETE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L191"></a><tt class="py-lineno">191</tt>  <tt class="py-line"> <tt class="py-number">130</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Attempt to use a file handle to an open disk partition for an operation other than raw disk I/O"</tt><tt class="py-op">,</tt> </tt>
<a name="L192"></a><tt class="py-lineno">192</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DIRECT_ACCESS_HANDLE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L193"></a><tt class="py-lineno">193</tt>  <tt class="py-line"> <tt class="py-number">131</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An attempt was made to move the file pointer before the beginning of the file"</tt><tt class="py-op">,</tt> </tt>
<a name="L194"></a><tt class="py-lineno">194</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NEGATIVE_SEEK"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L195"></a><tt class="py-lineno">195</tt>  <tt class="py-line"> <tt class="py-number">132</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The file pointer cannot be set on the specified device or file"</tt><tt class="py-op">,</tt> </tt>
<a name="L196"></a><tt class="py-lineno">196</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SEEK_ON_DEVICE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L197"></a><tt class="py-lineno">197</tt>  <tt class="py-line"> <tt class="py-number">133</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"A JOIN or SUBST command cannot be used for a drive that contains previously joined drives"</tt><tt class="py-op">,</tt> </tt>
<a name="L198"></a><tt class="py-lineno">198</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_IS_JOIN_TARGET"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L199"></a><tt class="py-lineno">199</tt>  <tt class="py-line"> <tt class="py-number">134</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An attempt was made to use a JOIN or SUBST command on a drive that has already been joined"</tt><tt class="py-op">,</tt> </tt>
<a name="L200"></a><tt class="py-lineno">200</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_IS_JOINED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L201"></a><tt class="py-lineno">201</tt>  <tt class="py-line"> <tt class="py-number">135</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An attempt was made to use a JOIN or SUBST command on a drive that has already been substituted"</tt><tt class="py-op">,</tt> </tt>
<a name="L202"></a><tt class="py-lineno">202</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_IS_SUBSTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L203"></a><tt class="py-lineno">203</tt>  <tt class="py-line"> <tt class="py-number">136</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system tried to delete the JOIN of a drive that is not joined"</tt><tt class="py-op">,</tt> </tt>
<a name="L204"></a><tt class="py-lineno">204</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NOT_JOINED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L205"></a><tt class="py-lineno">205</tt>  <tt class="py-line"> <tt class="py-number">137</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system tried to delete the substitution of a drive that is not substituted"</tt><tt class="py-op">,</tt> </tt>
<a name="L206"></a><tt class="py-lineno">206</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NOT_SUBSTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L207"></a><tt class="py-lineno">207</tt>  <tt class="py-line"> <tt class="py-number">138</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system tried to join a drive to a directory on a joined drive"</tt><tt class="py-op">,</tt> </tt>
<a name="L208"></a><tt class="py-lineno">208</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_JOIN_TO_JOIN"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L209"></a><tt class="py-lineno">209</tt>  <tt class="py-line"> <tt class="py-number">139</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system tried to substitute a drive to a directory on a substituted drive"</tt><tt class="py-op">,</tt> </tt>
<a name="L210"></a><tt class="py-lineno">210</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SUBST_TO_SUBST"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L211"></a><tt class="py-lineno">211</tt>  <tt class="py-line"> <tt class="py-number">140</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system tried to join a drive to a directory on a substituted drive"</tt><tt class="py-op">,</tt> </tt>
<a name="L212"></a><tt class="py-lineno">212</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_JOIN_TO_SUBST"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L213"></a><tt class="py-lineno">213</tt>  <tt class="py-line"> <tt class="py-number">141</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system tried to SUBST a drive to a directory on a joined drive"</tt><tt class="py-op">,</tt> </tt>
<a name="L214"></a><tt class="py-lineno">214</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SUBST_TO_JOIN"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L215"></a><tt class="py-lineno">215</tt>  <tt class="py-line"> <tt class="py-number">142</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system cannot perform a JOIN or SUBST at this time"</tt><tt class="py-op">,</tt> </tt>
<a name="L216"></a><tt class="py-lineno">216</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BUSY_DRIVE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L217"></a><tt class="py-lineno">217</tt>  <tt class="py-line"> <tt class="py-number">143</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system cannot join or substitute a drive to or for a directory on the same drive"</tt><tt class="py-op">,</tt> </tt>
<a name="L218"></a><tt class="py-lineno">218</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SAME_DRIVE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L219"></a><tt class="py-lineno">219</tt>  <tt class="py-line"> <tt class="py-number">144</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The directory is not a subdirectory of the root directory"</tt><tt class="py-op">,</tt> </tt>
<a name="L220"></a><tt class="py-lineno">220</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DIR_NOT_ROOT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L221"></a><tt class="py-lineno">221</tt>  <tt class="py-line"> <tt class="py-number">145</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The directory is not empty"</tt><tt class="py-op">,</tt> </tt>
<a name="L222"></a><tt class="py-lineno">222</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DIR_NOT_EMPTY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L223"></a><tt class="py-lineno">223</tt>  <tt class="py-line"> <tt class="py-number">146</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The path specified is being used in a substitute"</tt><tt class="py-op">,</tt> </tt>
<a name="L224"></a><tt class="py-lineno">224</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_IS_SUBST_PATH"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L225"></a><tt class="py-lineno">225</tt>  <tt class="py-line"> <tt class="py-number">147</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Not enough resources are available to process this command"</tt><tt class="py-op">,</tt> </tt>
<a name="L226"></a><tt class="py-lineno">226</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_IS_JOIN_PATH"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L227"></a><tt class="py-lineno">227</tt>  <tt class="py-line"> <tt class="py-number">148</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The path specified cannot be used at this time"</tt><tt class="py-op">,</tt> </tt>
<a name="L228"></a><tt class="py-lineno">228</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_PATH_BUSY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L229"></a><tt class="py-lineno">229</tt>  <tt class="py-line"> <tt class="py-number">149</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An attempt was made to join or substitute a drive for which a directory on the drive is the target of a previous substitute"</tt><tt class="py-op">,</tt> </tt>
<a name="L230"></a><tt class="py-lineno">230</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_IS_SUBST_TARGET"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L231"></a><tt class="py-lineno">231</tt>  <tt class="py-line"> <tt class="py-number">150</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"System trace information was not specified in your CONFIG.SYS file, or tracing is disallowed"</tt><tt class="py-op">,</tt> </tt>
<a name="L232"></a><tt class="py-lineno">232</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SYSTEM_TRACE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L233"></a><tt class="py-lineno">233</tt>  <tt class="py-line"> <tt class="py-number">151</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The number of specified semaphore events for DosMuxSemWait is not correct"</tt><tt class="py-op">,</tt> </tt>
<a name="L234"></a><tt class="py-lineno">234</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_EVENT_COUNT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L235"></a><tt class="py-lineno">235</tt>  <tt class="py-line"> <tt class="py-number">152</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"DosMuxSemWait did not execute; too many semaphores are already set"</tt><tt class="py-op">,</tt> </tt>
<a name="L236"></a><tt class="py-lineno">236</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_TOO_MANY_MUXWAITERS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L237"></a><tt class="py-lineno">237</tt>  <tt class="py-line"> <tt class="py-number">153</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The DosMuxSemWait list is not correct"</tt><tt class="py-op">,</tt> </tt>
<a name="L238"></a><tt class="py-lineno">238</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_LIST_FORMAT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L239"></a><tt class="py-lineno">239</tt>  <tt class="py-line"> <tt class="py-number">154</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The volume label you entered exceeds the label character limit of the target file system"</tt><tt class="py-op">,</tt> </tt>
<a name="L240"></a><tt class="py-lineno">240</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_LABEL_TOO_LONG"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L241"></a><tt class="py-lineno">241</tt>  <tt class="py-line"> <tt class="py-number">155</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Cannot create another thread"</tt><tt class="py-op">,</tt> </tt>
<a name="L242"></a><tt class="py-lineno">242</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_TOO_MANY_TCBS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L243"></a><tt class="py-lineno">243</tt>  <tt class="py-line"> <tt class="py-number">156</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The recipient process has refused the signal"</tt><tt class="py-op">,</tt> </tt>
<a name="L244"></a><tt class="py-lineno">244</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SIGNAL_REFUSED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L245"></a><tt class="py-lineno">245</tt>  <tt class="py-line"> <tt class="py-number">157</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The segment is already discarded and cannot be locked"</tt><tt class="py-op">,</tt> </tt>
<a name="L246"></a><tt class="py-lineno">246</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DISCARDED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L247"></a><tt class="py-lineno">247</tt>  <tt class="py-line"> <tt class="py-number">158</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The segment is already unlocked"</tt><tt class="py-op">,</tt> </tt>
<a name="L248"></a><tt class="py-lineno">248</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NOT_LOCKED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L249"></a><tt class="py-lineno">249</tt>  <tt class="py-line"> <tt class="py-number">159</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The address for the thread ID is not correct"</tt><tt class="py-op">,</tt> </tt>
<a name="L250"></a><tt class="py-lineno">250</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_THREADID_ADDR"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L251"></a><tt class="py-lineno">251</tt>  <tt class="py-line"> <tt class="py-number">160</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"One or more arguments are not correct"</tt><tt class="py-op">,</tt> </tt>
<a name="L252"></a><tt class="py-lineno">252</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_ARGUMENTS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L253"></a><tt class="py-lineno">253</tt>  <tt class="py-line"> <tt class="py-number">161</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The specified path is invalid"</tt><tt class="py-op">,</tt> </tt>
<a name="L254"></a><tt class="py-lineno">254</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_PATHNAME"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L255"></a><tt class="py-lineno">255</tt>  <tt class="py-line"> <tt class="py-number">162</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"A signal is already pending"</tt><tt class="py-op">,</tt> </tt>
<a name="L256"></a><tt class="py-lineno">256</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SIGNAL_PENDING"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L257"></a><tt class="py-lineno">257</tt>  <tt class="py-line"> <tt class="py-number">164</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"No more threads can be created in the system"</tt><tt class="py-op">,</tt> </tt>
<a name="L258"></a><tt class="py-lineno">258</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_MAX_THRDS_REACHED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L259"></a><tt class="py-lineno">259</tt>  <tt class="py-line"> <tt class="py-number">167</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Unable to lock a region of a file"</tt><tt class="py-op">,</tt> </tt>
<a name="L260"></a><tt class="py-lineno">260</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_LOCK_FAILED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L261"></a><tt class="py-lineno">261</tt>  <tt class="py-line"> <tt class="py-number">170</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The requested resource is in use"</tt><tt class="py-op">,</tt> </tt>
<a name="L262"></a><tt class="py-lineno">262</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BUSY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L263"></a><tt class="py-lineno">263</tt>  <tt class="py-line"> <tt class="py-number">171</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Device's command support detection is in progress"</tt><tt class="py-op">,</tt> </tt>
<a name="L264"></a><tt class="py-lineno">264</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DEVICE_SUPPORT_IN_PROGRESS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L265"></a><tt class="py-lineno">265</tt>  <tt class="py-line"> <tt class="py-number">173</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"A lock request was not outstanding for the supplied cancel region"</tt><tt class="py-op">,</tt> </tt>
<a name="L266"></a><tt class="py-lineno">266</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_CANCEL_VIOLATION"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L267"></a><tt class="py-lineno">267</tt>  <tt class="py-line"> <tt class="py-number">174</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The file system does not support atomic changes to the lock type"</tt><tt class="py-op">,</tt> </tt>
<a name="L268"></a><tt class="py-lineno">268</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_ATOMIC_LOCKS_NOT_SUPPORTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L269"></a><tt class="py-lineno">269</tt>  <tt class="py-line"> <tt class="py-number">180</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system detected a segment number that was not correct"</tt><tt class="py-op">,</tt> </tt>
<a name="L270"></a><tt class="py-lineno">270</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_SEGMENT_NUMBER"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L271"></a><tt class="py-lineno">271</tt>  <tt class="py-line"> <tt class="py-number">182</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operating system cannot run %1"</tt><tt class="py-op">,</tt> </tt>
<a name="L272"></a><tt class="py-lineno">272</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_ORDINAL"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L273"></a><tt class="py-lineno">273</tt>  <tt class="py-line"> <tt class="py-number">183</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Cannot create a file when that file already exists"</tt><tt class="py-op">,</tt> </tt>
<a name="L274"></a><tt class="py-lineno">274</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_ALREADY_EXISTS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L275"></a><tt class="py-lineno">275</tt>  <tt class="py-line"> <tt class="py-number">186</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The flag passed is not correct"</tt><tt class="py-op">,</tt> </tt>
<a name="L276"></a><tt class="py-lineno">276</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_FLAG_NUMBER"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L277"></a><tt class="py-lineno">277</tt>  <tt class="py-line"> <tt class="py-number">187</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The specified system semaphore name was not found"</tt><tt class="py-op">,</tt> </tt>
<a name="L278"></a><tt class="py-lineno">278</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SEM_NOT_FOUND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L279"></a><tt class="py-lineno">279</tt>  <tt class="py-line"> <tt class="py-number">188</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operating system cannot run %1"</tt><tt class="py-op">,</tt> </tt>
<a name="L280"></a><tt class="py-lineno">280</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_STARTING_CODESEG"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L281"></a><tt class="py-lineno">281</tt>  <tt class="py-line"> <tt class="py-number">189</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operating system cannot run %1"</tt><tt class="py-op">,</tt> </tt>
<a name="L282"></a><tt class="py-lineno">282</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_STACKSEG"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L283"></a><tt class="py-lineno">283</tt>  <tt class="py-line"> <tt class="py-number">190</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operating system cannot run %1"</tt><tt class="py-op">,</tt> </tt>
<a name="L284"></a><tt class="py-lineno">284</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_MODULETYPE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L285"></a><tt class="py-lineno">285</tt>  <tt class="py-line"> <tt class="py-number">191</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Cannot run %1 in Win32 mode"</tt><tt class="py-op">,</tt> </tt>
<a name="L286"></a><tt class="py-lineno">286</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_EXE_SIGNATURE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L287"></a><tt class="py-lineno">287</tt>  <tt class="py-line"> <tt class="py-number">192</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operating system cannot run %1"</tt><tt class="py-op">,</tt> </tt>
<a name="L288"></a><tt class="py-lineno">288</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_EXE_MARKED_INVALID"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L289"></a><tt class="py-lineno">289</tt>  <tt class="py-line"> <tt class="py-number">193</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"%1 is not a valid Win32 application"</tt><tt class="py-op">,</tt> </tt>
<a name="L290"></a><tt class="py-lineno">290</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_EXE_FORMAT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L291"></a><tt class="py-lineno">291</tt>  <tt class="py-line"> <tt class="py-number">194</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operating system cannot run %1"</tt><tt class="py-op">,</tt> </tt>
<a name="L292"></a><tt class="py-lineno">292</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_ITERATED_DATA_EXCEEDS_64k"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L293"></a><tt class="py-lineno">293</tt>  <tt class="py-line"> <tt class="py-number">195</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operating system cannot run %1"</tt><tt class="py-op">,</tt> </tt>
<a name="L294"></a><tt class="py-lineno">294</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_MINALLOCSIZE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L295"></a><tt class="py-lineno">295</tt>  <tt class="py-line"> <tt class="py-number">196</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operating system cannot run this application program"</tt><tt class="py-op">,</tt> </tt>
<a name="L296"></a><tt class="py-lineno">296</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DYNLINK_FROM_INVALID_RING"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L297"></a><tt class="py-lineno">297</tt>  <tt class="py-line"> <tt class="py-number">197</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operating system is not presently configured to run this application"</tt><tt class="py-op">,</tt> </tt>
<a name="L298"></a><tt class="py-lineno">298</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_IOPL_NOT_ENABLED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L299"></a><tt class="py-lineno">299</tt>  <tt class="py-line"> <tt class="py-number">198</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operating system cannot run %1"</tt><tt class="py-op">,</tt> </tt>
<a name="L300"></a><tt class="py-lineno">300</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_SEGDPL"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L301"></a><tt class="py-lineno">301</tt>  <tt class="py-line"> <tt class="py-number">199</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operating system cannot run this application program"</tt><tt class="py-op">,</tt> </tt>
<a name="L302"></a><tt class="py-lineno">302</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_AUTODATASEG_EXCEEDS_64k"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L303"></a><tt class="py-lineno">303</tt>  <tt class="py-line"> <tt class="py-number">200</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The code segment cannot be greater than or equal to 64K"</tt><tt class="py-op">,</tt> </tt>
<a name="L304"></a><tt class="py-lineno">304</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_RING2SEG_MUST_BE_MOVABLE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L305"></a><tt class="py-lineno">305</tt>  <tt class="py-line"> <tt class="py-number">201</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operating system cannot run %1"</tt><tt class="py-op">,</tt> </tt>
<a name="L306"></a><tt class="py-lineno">306</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_RELOC_CHAIN_XEEDS_SEGLIM"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L307"></a><tt class="py-lineno">307</tt>  <tt class="py-line"> <tt class="py-number">202</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The operating system cannot run %1"</tt><tt class="py-op">,</tt> </tt>
<a name="L308"></a><tt class="py-lineno">308</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INFLOOP_IN_RELOC_CHAIN"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L309"></a><tt class="py-lineno">309</tt>  <tt class="py-line"> <tt class="py-number">203</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system could not find the environment option that was entered"</tt><tt class="py-op">,</tt> </tt>
<a name="L310"></a><tt class="py-lineno">310</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_ENVVAR_NOT_FOUND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L311"></a><tt class="py-lineno">311</tt>  <tt class="py-line"> <tt class="py-number">205</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"No process in the command subtree has a signal handler"</tt><tt class="py-op">,</tt> </tt>
<a name="L312"></a><tt class="py-lineno">312</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NO_SIGNAL_SENT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L313"></a><tt class="py-lineno">313</tt>  <tt class="py-line"> <tt class="py-number">206</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The filename or extension is too long"</tt><tt class="py-op">,</tt> </tt>
<a name="L314"></a><tt class="py-lineno">314</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_FILENAME_EXCED_RANGE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L315"></a><tt class="py-lineno">315</tt>  <tt class="py-line"> <tt class="py-number">207</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The ring 2 stack is in use"</tt><tt class="py-op">,</tt> </tt>
<a name="L316"></a><tt class="py-lineno">316</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_RING2_STACK_IN_USE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L317"></a><tt class="py-lineno">317</tt>  <tt class="py-line"> <tt class="py-number">208</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The global filename characters, * or ?, are entered incorrectly or too many global filename characters are specified"</tt><tt class="py-op">,</tt> </tt>
<a name="L318"></a><tt class="py-lineno">318</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_META_EXPANSION_TOO_LONG"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L319"></a><tt class="py-lineno">319</tt>  <tt class="py-line"> <tt class="py-number">209</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The signal being posted is not correct"</tt><tt class="py-op">,</tt> </tt>
<a name="L320"></a><tt class="py-lineno">320</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_SIGNAL_NUMBER"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L321"></a><tt class="py-lineno">321</tt>  <tt class="py-line"> <tt class="py-number">210</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The signal handler cannot be set"</tt><tt class="py-op">,</tt> </tt>
<a name="L322"></a><tt class="py-lineno">322</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_THREAD_1_INACTIVE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L323"></a><tt class="py-lineno">323</tt>  <tt class="py-line"> <tt class="py-number">212</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The segment is locked and cannot be reallocated"</tt><tt class="py-op">,</tt> </tt>
<a name="L324"></a><tt class="py-lineno">324</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_LOCKED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L325"></a><tt class="py-lineno">325</tt>  <tt class="py-line"> <tt class="py-number">214</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Too many dynamic-link modules are attached to this program or dynamic-link module"</tt><tt class="py-op">,</tt> </tt>
<a name="L326"></a><tt class="py-lineno">326</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_TOO_MANY_MODULES"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L327"></a><tt class="py-lineno">327</tt>  <tt class="py-line"> <tt class="py-number">215</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Cannot nest calls to LoadModule"</tt><tt class="py-op">,</tt> </tt>
<a name="L328"></a><tt class="py-lineno">328</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NESTING_NOT_ALLOWED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L329"></a><tt class="py-lineno">329</tt>  <tt class="py-line"> <tt class="py-number">216</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher"</tt><tt class="py-op">,</tt> </tt>
<a name="L330"></a><tt class="py-lineno">330</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_EXE_MACHINE_TYPE_MISMATCH"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L331"></a><tt class="py-lineno">331</tt>  <tt class="py-line"> <tt class="py-number">217</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The image file %1 is signed, unable to modify"</tt><tt class="py-op">,</tt> </tt>
<a name="L332"></a><tt class="py-lineno">332</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_EXE_CANNOT_MODIFY_SIGNED_BINARY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L333"></a><tt class="py-lineno">333</tt>  <tt class="py-line"> <tt class="py-number">218</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The image file %1 is strong signed, unable to modify"</tt><tt class="py-op">,</tt> </tt>
<a name="L334"></a><tt class="py-lineno">334</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_EXE_CANNOT_MODIFY_STRONG_SIGNED_BINARY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L335"></a><tt class="py-lineno">335</tt>  <tt class="py-line"> <tt class="py-number">220</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"This file is checked out or locked for editing by another user"</tt><tt class="py-op">,</tt> </tt>
<a name="L336"></a><tt class="py-lineno">336</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_FILE_CHECKED_OUT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L337"></a><tt class="py-lineno">337</tt>  <tt class="py-line"> <tt class="py-number">221</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The file must be checked out before saving changes"</tt><tt class="py-op">,</tt> </tt>
<a name="L338"></a><tt class="py-lineno">338</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_CHECKOUT_REQUIRED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L339"></a><tt class="py-lineno">339</tt>  <tt class="py-line"> <tt class="py-number">222</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The file type being saved or retrieved has been blocked"</tt><tt class="py-op">,</tt> </tt>
<a name="L340"></a><tt class="py-lineno">340</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_FILE_TYPE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L341"></a><tt class="py-lineno">341</tt>  <tt class="py-line"> <tt class="py-number">223</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The file size exceeds the limit allowed and cannot be saved"</tt><tt class="py-op">,</tt> </tt>
<a name="L342"></a><tt class="py-lineno">342</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_FILE_TOO_LARGE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L343"></a><tt class="py-lineno">343</tt>  <tt class="py-line"> <tt class="py-number">224</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Access Denied. Before opening files in this location, you must first add the web site to your trusted sites list, browse to the web site, and select the option to login automatically"</tt><tt class="py-op">,</tt> </tt>
<a name="L344"></a><tt class="py-lineno">344</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_FORMS_AUTH_REQUIRED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L345"></a><tt class="py-lineno">345</tt>  <tt class="py-line"> <tt class="py-number">225</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Operation did not complete successfully because the file contains a virus or potentially unwanted software"</tt><tt class="py-op">,</tt> </tt>
<a name="L346"></a><tt class="py-lineno">346</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_VIRUS_INFECTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L347"></a><tt class="py-lineno">347</tt>  <tt class="py-line"> <tt class="py-number">226</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"This file contains a virus or potentially unwanted software and cannot be opened. Due to the nature of this virus or potentially unwanted software, the file has been removed from this location"</tt><tt class="py-op">,</tt> </tt>
<a name="L348"></a><tt class="py-lineno">348</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_VIRUS_DELETED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L349"></a><tt class="py-lineno">349</tt>  <tt class="py-line"> <tt class="py-number">229</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The pipe is local"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_PIPE_LOCAL"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L350"></a><tt class="py-lineno">350</tt>  <tt class="py-line"> <tt class="py-number">230</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The pipe state is invalid"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_PIPE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L351"></a><tt class="py-lineno">351</tt>  <tt class="py-line"> <tt class="py-number">231</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"All pipe instances are busy"</tt><tt class="py-op">,</tt> </tt>
<a name="L352"></a><tt class="py-lineno">352</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_PIPE_BUSY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L353"></a><tt class="py-lineno">353</tt>  <tt class="py-line"> <tt class="py-number">232</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The pipe is being closed"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NO_DATA"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L354"></a><tt class="py-lineno">354</tt>  <tt class="py-line"> <tt class="py-number">233</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"No process is on the other end of the pipe"</tt><tt class="py-op">,</tt> </tt>
<a name="L355"></a><tt class="py-lineno">355</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_PIPE_NOT_CONNECTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L356"></a><tt class="py-lineno">356</tt>  <tt class="py-line"> <tt class="py-number">234</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"More data is available"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_MORE_DATA"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L357"></a><tt class="py-lineno">357</tt>  <tt class="py-line"> <tt class="py-number">240</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The session was canceled"</tt><tt class="py-op">,</tt> </tt>
<a name="L358"></a><tt class="py-lineno">358</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_VC_DISCONNECTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L359"></a><tt class="py-lineno">359</tt>  <tt class="py-line"> <tt class="py-number">254</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The specified extended attribute name was invalid"</tt><tt class="py-op">,</tt> </tt>
<a name="L360"></a><tt class="py-lineno">360</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_EA_NAME"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L361"></a><tt class="py-lineno">361</tt>  <tt class="py-line"> <tt class="py-number">255</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The extended attributes are inconsistent"</tt><tt class="py-op">,</tt> </tt>
<a name="L362"></a><tt class="py-lineno">362</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_EA_LIST_INCONSISTENT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L363"></a><tt class="py-lineno">363</tt>  <tt class="py-line"> <tt class="py-number">258</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The wait operation timed out"</tt><tt class="py-op">,</tt> <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"WAIT_TIMEOUT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L364"></a><tt class="py-lineno">364</tt>  <tt class="py-line"> <tt class="py-number">259</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"No more data is available"</tt><tt class="py-op">,</tt> </tt>
<a name="L365"></a><tt class="py-lineno">365</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NO_MORE_ITEMS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L366"></a><tt class="py-lineno">366</tt>  <tt class="py-line"> <tt class="py-number">266</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The copy functions cannot be used"</tt><tt class="py-op">,</tt> </tt>
<a name="L367"></a><tt class="py-lineno">367</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_CANNOT_COPY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L368"></a><tt class="py-lineno">368</tt>  <tt class="py-line"> <tt class="py-number">267</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The directory name is invalid"</tt><tt class="py-op">,</tt> </tt>
<a name="L369"></a><tt class="py-lineno">369</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DIRECTORY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L370"></a><tt class="py-lineno">370</tt>  <tt class="py-line"> <tt class="py-number">275</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The extended attributes did not fit in the buffer"</tt><tt class="py-op">,</tt> </tt>
<a name="L371"></a><tt class="py-lineno">371</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_EAS_DIDNT_FIT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L372"></a><tt class="py-lineno">372</tt>  <tt class="py-line"> <tt class="py-number">276</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The extended attribute file on the mounted file system is corrupt"</tt><tt class="py-op">,</tt> </tt>
<a name="L373"></a><tt class="py-lineno">373</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_EA_FILE_CORRUPT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L374"></a><tt class="py-lineno">374</tt>  <tt class="py-line"> <tt class="py-number">277</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The extended attribute table file is full"</tt><tt class="py-op">,</tt> </tt>
<a name="L375"></a><tt class="py-lineno">375</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_EA_TABLE_FULL"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L376"></a><tt class="py-lineno">376</tt>  <tt class="py-line"> <tt class="py-number">278</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The specified extended attribute handle is invalid"</tt><tt class="py-op">,</tt> </tt>
<a name="L377"></a><tt class="py-lineno">377</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_EA_HANDLE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L378"></a><tt class="py-lineno">378</tt>  <tt class="py-line"> <tt class="py-number">282</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The mounted file system does not support extended attributes"</tt><tt class="py-op">,</tt> </tt>
<a name="L379"></a><tt class="py-lineno">379</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_EAS_NOT_SUPPORTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L380"></a><tt class="py-lineno">380</tt>  <tt class="py-line"> <tt class="py-number">288</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Attempt to release mutex not owned by caller"</tt><tt class="py-op">,</tt> </tt>
<a name="L381"></a><tt class="py-lineno">381</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NOT_OWNER"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L382"></a><tt class="py-lineno">382</tt>  <tt class="py-line"> <tt class="py-number">298</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Too many posts were made to a semaphore"</tt><tt class="py-op">,</tt> </tt>
<a name="L383"></a><tt class="py-lineno">383</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_TOO_MANY_POSTS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L384"></a><tt class="py-lineno">384</tt>  <tt class="py-line"> <tt class="py-number">299</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Only part of a ReadProcessMemory or WriteProcessMemory request was completed"</tt><tt class="py-op">,</tt> </tt>
<a name="L385"></a><tt class="py-lineno">385</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_PARTIAL_COPY"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L386"></a><tt class="py-lineno">386</tt>  <tt class="py-line"> <tt class="py-number">300</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The oplock request is denied"</tt><tt class="py-op">,</tt> </tt>
<a name="L387"></a><tt class="py-lineno">387</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_OPLOCK_NOT_GRANTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L388"></a><tt class="py-lineno">388</tt>  <tt class="py-line"> <tt class="py-number">301</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An invalid oplock acknowledgment was received by the system"</tt><tt class="py-op">,</tt> </tt>
<a name="L389"></a><tt class="py-lineno">389</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_OPLOCK_PROTOCOL"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L390"></a><tt class="py-lineno">390</tt>  <tt class="py-line"> <tt class="py-number">302</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The volume is too fragmented to complete this operation"</tt><tt class="py-op">,</tt> </tt>
<a name="L391"></a><tt class="py-lineno">391</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DISK_TOO_FRAGMENTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L392"></a><tt class="py-lineno">392</tt>  <tt class="py-line"> <tt class="py-number">303</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The file cannot be opened because it is in the process of being deleted"</tt><tt class="py-op">,</tt> </tt>
<a name="L393"></a><tt class="py-lineno">393</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DELETE_PENDING"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L394"></a><tt class="py-lineno">394</tt>  <tt class="py-line"> <tt class="py-number">304</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Short name settings may not be changed on this volume due to the global registry setting"</tt><tt class="py-op">,</tt> </tt>
<a name="L395"></a><tt class="py-lineno">395</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L396"></a><tt class="py-lineno">396</tt>  <tt class="py-line"> <tt class="py-number">305</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Short names are not enabled on this volume"</tt><tt class="py-op">,</tt> </tt>
<a name="L397"></a><tt class="py-lineno">397</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SHORT_NAMES_NOT_ENABLED_ON_VOLUME"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L398"></a><tt class="py-lineno">398</tt>  <tt class="py-line"> <tt class="py-number">306</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The security stream for the given volume is in an inconsistent state. Please run CHKDSK on the volume"</tt><tt class="py-op">,</tt> </tt>
<a name="L399"></a><tt class="py-lineno">399</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SECURITY_STREAM_IS_INCONSISTENT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L400"></a><tt class="py-lineno">400</tt>  <tt class="py-line"> <tt class="py-number">307</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"A requested file lock operation cannot be processed due to an invalid byte range"</tt><tt class="py-op">,</tt> </tt>
<a name="L401"></a><tt class="py-lineno">401</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_LOCK_RANGE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L402"></a><tt class="py-lineno">402</tt>  <tt class="py-line"> <tt class="py-number">308</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The subsystem needed to support the image type is not present"</tt><tt class="py-op">,</tt> </tt>
<a name="L403"></a><tt class="py-lineno">403</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_IMAGE_SUBSYSTEM_NOT_PRESENT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L404"></a><tt class="py-lineno">404</tt>  <tt class="py-line"> <tt class="py-number">309</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The specified file already has a notification GUID associated with it"</tt><tt class="py-op">,</tt> </tt>
<a name="L405"></a><tt class="py-lineno">405</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NOTIFICATION_GUID_ALREADY_DEFINED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L406"></a><tt class="py-lineno">406</tt>  <tt class="py-line"> <tt class="py-number">310</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An invalid exception handler routine has been detected"</tt><tt class="py-op">,</tt> </tt>
<a name="L407"></a><tt class="py-lineno">407</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_EXCEPTION_HANDLER"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L408"></a><tt class="py-lineno">408</tt>  <tt class="py-line"> <tt class="py-number">311</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Duplicate privileges were specified for the token"</tt><tt class="py-op">,</tt> </tt>
<a name="L409"></a><tt class="py-lineno">409</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DUPLICATE_PRIVILEGES"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L410"></a><tt class="py-lineno">410</tt>  <tt class="py-line"> <tt class="py-number">312</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"No ranges for the specified operation were able to be processed"</tt><tt class="py-op">,</tt> </tt>
<a name="L411"></a><tt class="py-lineno">411</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NO_RANGES_PROCESSED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L412"></a><tt class="py-lineno">412</tt>  <tt class="py-line"> <tt class="py-number">313</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Operation is not allowed on a file system internal file"</tt><tt class="py-op">,</tt> </tt>
<a name="L413"></a><tt class="py-lineno">413</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NOT_ALLOWED_ON_SYSTEM_FILE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L414"></a><tt class="py-lineno">414</tt>  <tt class="py-line"> <tt class="py-number">314</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The physical resources of this disk have been exhausted"</tt><tt class="py-op">,</tt> </tt>
<a name="L415"></a><tt class="py-lineno">415</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DISK_RESOURCES_EXHAUSTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L416"></a><tt class="py-lineno">416</tt>  <tt class="py-line"> <tt class="py-number">315</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The token representing the data is invalid"</tt><tt class="py-op">,</tt> </tt>
<a name="L417"></a><tt class="py-lineno">417</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_TOKEN"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L418"></a><tt class="py-lineno">418</tt>  <tt class="py-line"> <tt class="py-number">316</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The device does not support the command feature"</tt><tt class="py-op">,</tt> </tt>
<a name="L419"></a><tt class="py-lineno">419</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DEVICE_FEATURE_NOT_SUPPORTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L420"></a><tt class="py-lineno">420</tt>  <tt class="py-line"> <tt class="py-number">317</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The system cannot find message text for message number 0x%1 in the message file for %2"</tt><tt class="py-op">,</tt> </tt>
<a name="L421"></a><tt class="py-lineno">421</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_MR_MID_NOT_FOUND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L422"></a><tt class="py-lineno">422</tt>  <tt class="py-line"> <tt class="py-number">318</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The scope specified was not found"</tt><tt class="py-op">,</tt> </tt>
<a name="L423"></a><tt class="py-lineno">423</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SCOPE_NOT_FOUND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L424"></a><tt class="py-lineno">424</tt>  <tt class="py-line"> <tt class="py-number">319</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The Central Access Policy specified is not defined on the target machine"</tt><tt class="py-op">,</tt> </tt>
<a name="L425"></a><tt class="py-lineno">425</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_UNDEFINED_SCOPE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L426"></a><tt class="py-lineno">426</tt>  <tt class="py-line"> <tt class="py-number">320</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The Central Access Policy obtained from Active Directory is invalid"</tt><tt class="py-op">,</tt> </tt>
<a name="L427"></a><tt class="py-lineno">427</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_CAP"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L428"></a><tt class="py-lineno">428</tt>  <tt class="py-line"> <tt class="py-number">321</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The device is unreachable"</tt><tt class="py-op">,</tt> </tt>
<a name="L429"></a><tt class="py-lineno">429</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DEVICE_UNREACHABLE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L430"></a><tt class="py-lineno">430</tt>  <tt class="py-line"> <tt class="py-number">322</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The target device has insufficient resources to complete the operation"</tt><tt class="py-op">,</tt> </tt>
<a name="L431"></a><tt class="py-lineno">431</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DEVICE_NO_RESOURCES"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L432"></a><tt class="py-lineno">432</tt>  <tt class="py-line"> <tt class="py-number">323</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"A data integrity checksum error occurred. Data in the file stream is corrupt"</tt><tt class="py-op">,</tt> </tt>
<a name="L433"></a><tt class="py-lineno">433</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DATA_CHECKSUM_ERROR"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L434"></a><tt class="py-lineno">434</tt>  <tt class="py-line"> <tt class="py-number">324</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An attempt was made to modify both a KERNEL and normal Extended Attribute (EA) in the same operation"</tt><tt class="py-op">,</tt> </tt>
<a name="L435"></a><tt class="py-lineno">435</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INTERMIXED_KERNEL_EA_OPERATION"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L436"></a><tt class="py-lineno">436</tt>  <tt class="py-line"> <tt class="py-number">326</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Device does not support file-level TRIM"</tt><tt class="py-op">,</tt> </tt>
<a name="L437"></a><tt class="py-lineno">437</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_FILE_LEVEL_TRIM_NOT_SUPPORTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L438"></a><tt class="py-lineno">438</tt>  <tt class="py-line"> <tt class="py-number">327</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The command specified a data offset that does not align to the device's granularity/alignment"</tt><tt class="py-op">,</tt> </tt>
<a name="L439"></a><tt class="py-lineno">439</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_OFFSET_ALIGNMENT_VIOLATION"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L440"></a><tt class="py-lineno">440</tt>  <tt class="py-line"> <tt class="py-number">328</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The command specified an invalid field in its parameter list"</tt><tt class="py-op">,</tt> </tt>
<a name="L441"></a><tt class="py-lineno">441</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_FIELD_IN_PARAMETER_LIST"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L442"></a><tt class="py-lineno">442</tt>  <tt class="py-line"> <tt class="py-number">329</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An operation is currently in progress with the device"</tt><tt class="py-op">,</tt> </tt>
<a name="L443"></a><tt class="py-lineno">443</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_OPERATION_IN_PROGRESS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L444"></a><tt class="py-lineno">444</tt>  <tt class="py-line"> <tt class="py-number">330</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An attempt was made to send down the command via an invalid path to the target device"</tt><tt class="py-op">,</tt> </tt>
<a name="L445"></a><tt class="py-lineno">445</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_BAD_DEVICE_PATH"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L446"></a><tt class="py-lineno">446</tt>  <tt class="py-line"> <tt class="py-number">331</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The command specified a number of descriptors that exceeded the maximum supported by the device"</tt><tt class="py-op">,</tt> </tt>
<a name="L447"></a><tt class="py-lineno">447</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_TOO_MANY_DESCRIPTORS"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L448"></a><tt class="py-lineno">448</tt>  <tt class="py-line"> <tt class="py-number">332</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Scrub is disabled on the specified file"</tt><tt class="py-op">,</tt> </tt>
<a name="L449"></a><tt class="py-lineno">449</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_SCRUB_DATA_DISABLED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L450"></a><tt class="py-lineno">450</tt>  <tt class="py-line"> <tt class="py-number">333</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The storage device does not provide redundancy"</tt><tt class="py-op">,</tt> </tt>
<a name="L451"></a><tt class="py-lineno">451</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_NOT_REDUNDANT_STORAGE"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L452"></a><tt class="py-lineno">452</tt>  <tt class="py-line"> <tt class="py-number">334</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An operation is not supported on a resident file"</tt><tt class="py-op">,</tt> </tt>
<a name="L453"></a><tt class="py-lineno">453</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_RESIDENT_FILE_NOT_SUPPORTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L454"></a><tt class="py-lineno">454</tt>  <tt class="py-line"> <tt class="py-number">335</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An operation is not supported on a compressed file"</tt><tt class="py-op">,</tt> </tt>
<a name="L455"></a><tt class="py-lineno">455</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_COMPRESSED_FILE_NOT_SUPPORTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L456"></a><tt class="py-lineno">456</tt>  <tt class="py-line"> <tt class="py-number">336</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"An operation is not supported on a directory"</tt><tt class="py-op">,</tt> </tt>
<a name="L457"></a><tt class="py-lineno">457</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_DIRECTORY_NOT_SUPPORTED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L458"></a><tt class="py-lineno">458</tt>  <tt class="py-line"> <tt class="py-number">350</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"No action was taken as a system reboot is required"</tt><tt class="py-op">,</tt> </tt>
<a name="L459"></a><tt class="py-lineno">459</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_FAIL_NOACTION_REBOOT"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L460"></a><tt class="py-lineno">460</tt>  <tt class="py-line"> <tt class="py-number">351</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The shutdown operation failed"</tt><tt class="py-op">,</tt> </tt>
<a name="L461"></a><tt class="py-lineno">461</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_FAIL_SHUTDOWN"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L462"></a><tt class="py-lineno">462</tt>  <tt class="py-line"> <tt class="py-number">352</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The restart operation failed"</tt><tt class="py-op">,</tt> </tt>
<a name="L463"></a><tt class="py-lineno">463</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_FAIL_RESTART"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L464"></a><tt class="py-lineno">464</tt>  <tt class="py-line"> <tt class="py-number">353</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The maximum number of sessions has been reached"</tt><tt class="py-op">,</tt> </tt>
<a name="L465"></a><tt class="py-lineno">465</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_MAX_SESSIONS_REACHED"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L466"></a><tt class="py-lineno">466</tt>  <tt class="py-line"> <tt class="py-number">400</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The thread is already in background processing mode"</tt><tt class="py-op">,</tt> </tt>
<a name="L467"></a><tt class="py-lineno">467</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_THREAD_MODE_ALREADY_BACKGROUND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L468"></a><tt class="py-lineno">468</tt>  <tt class="py-line"> <tt class="py-number">401</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The thread is not in background processing mode"</tt><tt class="py-op">,</tt> </tt>
<a name="L469"></a><tt class="py-lineno">469</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_THREAD_MODE_NOT_BACKGROUND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L470"></a><tt class="py-lineno">470</tt>  <tt class="py-line"> <tt class="py-number">402</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The process is already in background processing mode"</tt><tt class="py-op">,</tt> </tt>
<a name="L471"></a><tt class="py-lineno">471</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_PROCESS_MODE_ALREADY_BACKGROUND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L472"></a><tt class="py-lineno">472</tt>  <tt class="py-line"> <tt class="py-number">403</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"The process is not in background processing mode"</tt><tt class="py-op">,</tt> </tt>
<a name="L473"></a><tt class="py-lineno">473</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_PROCESS_MODE_NOT_BACKGROUND"</tt><tt class="py-op">}</tt><tt class="py-op">,</tt> </tt>
<a name="L474"></a><tt class="py-lineno">474</tt>  <tt class="py-line"> <tt class="py-number">487</tt><tt class="py-op">:</tt> <tt class="py-op">{</tt><tt class="py-string">"description"</tt><tt class="py-op">:</tt> <tt class="py-string">"Attempt to access invalid address"</tt><tt class="py-op">,</tt> </tt>
<a name="L475"></a><tt class="py-lineno">475</tt>  <tt class="py-line">       <tt class="py-string">"name"</tt><tt class="py-op">:</tt> <tt class="py-string">"ERROR_INVALID_ADDRESS"</tt><tt class="py-op">}</tt> </tt>
<a name="L476"></a><tt class="py-lineno">476</tt>  <tt class="py-line"><tt class="py-op">}</tt> </tt>
<a name="L477"></a><tt class="py-lineno">477</tt>  <tt class="py-line"> </tt>
<a name="get_error_string"></a><div id="get_error_string-def"><a name="L478"></a><tt class="py-lineno">478</tt> <a class="py-toggle" href="#" id="get_error_string-toggle" onclick="return toggle('get_error_string');">-</a><tt class="py-line"><tt class="py-keyword">def</tt> <a class="py-def-name" href="lib.common.errors-module.html#get_error_string">get_error_string</a><tt class="py-op">(</tt><tt class="py-param">error_code</tt><tt class="py-op">)</tt><tt class="py-op">:</tt> </tt>
</div><div id="get_error_string-collapsed" style="display:none;" pad="+++" indent="++++"></div><div id="get_error_string-expanded"><a name="L479"></a><tt class="py-lineno">479</tt>  <tt class="py-line">    <tt class="py-docstring">"""Error code lookup.</tt> </tt>
<a name="L480"></a><tt class="py-lineno">480</tt>  <tt class="py-line"><tt class="py-docstring">    @param error_code: error code.</tt> </tt>
<a name="L481"></a><tt class="py-lineno">481</tt>  <tt class="py-line"><tt class="py-docstring">    @return: error description if found.</tt> </tt>
<a name="L482"></a><tt class="py-lineno">482</tt>  <tt class="py-line"><tt class="py-docstring">    """</tt> </tt>
<a name="L483"></a><tt class="py-lineno">483</tt>  <tt class="py-line">    <tt class="py-keyword">if</tt> <tt class="py-name">error_code</tt> <tt class="py-keyword">in</tt> <tt id="link-1" class="py-name"><a title="lib.common.errors.ERRORS" class="py-name" href="#" onclick="return doclink('link-1', 'ERRORS', 'link-0');">ERRORS</a></tt><tt class="py-op">:</tt> </tt>
<a name="L484"></a><tt class="py-lineno">484</tt>  <tt class="py-line">        <tt class="py-keyword">return</tt> <tt class="py-string">"%s (%s)"</tt> <tt class="py-op">%</tt> <tt class="py-op">(</tt><tt id="link-2" class="py-name"><a title="lib.common.errors.ERRORS" class="py-name" href="#" onclick="return doclink('link-2', 'ERRORS', 'link-0');">ERRORS</a></tt><tt class="py-op">[</tt><tt class="py-name">error_code</tt><tt class="py-op">]</tt><tt class="py-op">[</tt><tt class="py-string">"description"</tt><tt class="py-op">]</tt><tt class="py-op">,</tt> <tt id="link-3" class="py-name"><a title="lib.common.errors.ERRORS" class="py-name" href="#" onclick="return doclink('link-3', 'ERRORS', 'link-0');">ERRORS</a></tt><tt class="py-op">[</tt><tt class="py-name">error_code</tt><tt class="py-op">]</tt><tt class="py-op">[</tt><tt class="py-string">"name"</tt><tt class="py-op">]</tt><tt class="py-op">)</tt> </tt>
<a name="L485"></a><tt class="py-lineno">485</tt>  <tt class="py-line">    <tt class="py-keyword">else</tt><tt class="py-op">:</tt> </tt>
<a name="L486"></a><tt class="py-lineno">486</tt>  <tt class="py-line">        <tt class="py-keyword">return</tt> <tt class="py-name">str</tt><tt class="py-op">(</tt><tt class="py-name">error_code</tt><tt class="py-op">)</tt> </tt>
</div><a name="L487"></a><tt class="py-lineno">487</tt>  <tt class="py-line"> </tt><script type="text/javascript">
<!--
expandto(location.href);
// -->
</script>
</pre>
<br />
<!-- ==================== NAVIGATION BAR ==================== -->
<table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">

  <!-- Tree link -->
      <th>&nbsp;&nbsp;&nbsp;<a
        href="module-tree.html">Trees</a>&nbsp;&nbsp;&nbsp;</th>

  <!-- Index link -->
      <th>&nbsp;&nbsp;&nbsp;<a
        href="identifier-index.html">Indices</a>&nbsp;&nbsp;&nbsp;</th>

  <!-- Help link -->
      <th>&nbsp;&nbsp;&nbsp;<a
        href="help.html">Help</a>&nbsp;&nbsp;&nbsp;</th>

  <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://cuckoosandbox.org">Cuckoo Sandbox</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Mon Jan 11 19:29:13 2016
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>

<script type="text/javascript">
  <!--
  // Private objects are initially displayed (because if
  // javascript is turned off then we want them to be
  // visible); but by default, we want to hide them.  So hide
  // them unless we have a cookie that says to show them.
  checkCookie();
  // -->
</script>
</body>
</html>
